server:
  port: 8090
spring:
  application:
    name: 241DSWSpringMSDemo01Student
  config:
    import: optional:configserver:http://localhost:8888
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://137.184.120.127:5432/studentDb
    username: modulo4
    password: modulo4
  jpa:
    hibernate:
      ddl-auto: create
    #database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect      

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

